parameters:
#    ahead_cms.example.class: SkogstadMedia\Bundle\AheadCmsBundle\Example

services:
#    ahead_cms.example:
#        class: %ahead_cms.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
